env:
  TERM: alacritty

window:
  padding:
    x: 8
    y: 8

  title: Alacritty

scrolling:
  history: 10000

font:
  normal:
    family: mononoki
    style: Regular
  
  bold:
    family: mononoki
    style: Bold

  italic:
    family: mononoki
    style: Italic

  bold_italic:
    family: mononoki
    style: Bold Italic

  size: 8.0

colors:
  # Default color
  primary:
    background: '0x1c1d20'
    foreground: '0xc0c5ce'
  # Normal colors
  normal:
    black:   '0x1c1d20'
    red:     '0xbf616a'
    green:   '0xa3be8c'
    yellow:  '0xebcb8b'
    blue:    '0x8fa1b3'
    magenta: '0xb48ead'
    cyan:    '0x96b5b4'
    white:   '0xc0c5ce'
  # Bright colors
  bright:
    black:   '0x65737e'
    red:     '0xbf616a'
    green:   '0xa3be8c'
    yellow:  '0xebcb8b'
    blue:    '0x8fa1b3'
    magenta: '0xb48ead'
    cyan:    '0x96b5b4'
    white:   '0xc0c5ce'                                                                                  
