#!/bin/bash

NORMAL="\e[21m\033[0m"
BOLD="\e[1m\033[34m"
ERR_BOLD="\e[1m\033[31m"
ITALICS="\e[3m"
DIM="\e[2m"
RESET="\e[0m"

while getopts "::f" opt; do
    case ${opt} in
        f  ) OPT="f"
            ;;
        \? ) printf "Invalid option.\n\tUsage: install [-f]\n"
             exit 1
            ;;
    esac
done

output() {
    printf "${BOLD}source: ${NORMAL}%-15s${RESET} | " "$BASE"
    printf "${BOLD}link: ${NORMAL}$HOME/$BASE ${RESET}\n"
}

failed() {
    printf "\t${ERR_BOLD}ERROR${NORMAL} $OUT\n"
}

printf "${ITALICS}${DIM}Generating links...${RESET}\n\n"

for FILE in home/.*; do
    BASE=$(basename "$FILE")

    if [ "$BASE" != ".." ] && [ "$BASE" != "." ]; then
        output
        # save stderr output to variable to print in failed()
        OUT=$(ln -sn$OPT "$(pwd)/$FILE" "$HOME/$BASE" 2>&1)
        if [ $? != 0 ]; then
            failed
        fi
    fi
done

printf '\n'
