#!/bin/sh

NORMAL="\e[21m\033[0m"
BOLD="\e[1m\033[34m"
ERR_BOLD="\e[1m\033[31m"
ITALICS="\e[3m"
DIM="\e[2m"
RESET="\e[0m"

output() {
    printf '\n%b%s%b%-15s%s%b%s%b%-15s' "$BOLD" "source: " "$NORMAL" "$BASE" " | " "$BOLD" "link: " "$NORMAL" "$HOME/$BASE"
}

failed() {
    printf ' | %b%s: %b%s' "$ERR_BOLD" "ERROR" "$NORMAL" "$OUT"
}

printf '%b%b%s%b\n' "$ITALICS" "$DIM" "Generating links..." "$RESET"

for FILE in home/.*; do
    BASE=$(basename "$FILE")

    if [ "$BASE" != ".." ] && [ "$BASE" != "." ]; then
        output
        # save stderr output to variable to print in failed()
        OUT=$(ln -sfn "$(pwd)/$FILE" "$HOME/$BASE" 2>&1)
        if [ $? != 0 ]; then
            failed
        fi
    fi
done

printf '\n'
