#! /bin/sh

pgrep sxhkd || sxhkd &
xsetroot -cursor_name left_ptr &

pkill polybar
polybar test &

pkill picom
picom &

bspc monitor -d     

bspc config top_padding 40

bspc config border_width         0
bspc config window_gap          10

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a discord desktop='^3' state=tiled follow=on
